### ISSUE TITLE
index.js contains incorrect import

### ISSUE THREAD

**Issue by slavafomin** [RobinHerbots/inputmask.phone#2]
Hello!

Thank you for this library!

But, the `index.js` file, provided by the `1.0.3` version of he package contains an incorrect import statement.

It is:

`module.exports = require("./dist/inputmask/inputmask.phone.extensions");`

However, it should be:

`module.exports = require("./dist/inputmask.phone/inputmask.phone.extensions.js");`

The workaround is to import the target module directly:

`import 'inputmask.phone/dist/inputmask.phone/inputmask.phone.extensions';`

**Comment by RobinHerbots** [comment]
@slavafomin , 

Thx for the feedback.  I pushed a new version with the fix.
