### ISSUE TITLE
France mask typo

### ISSUE THREAD

**Issue by macfurin** [RobinHerbots/inputmask.phone#3]
The mask for France should be` +33-#-##-##-##` instead of:
```
mask: "+33(###)###-###",
                cc: "FR",
                cd: "France",
                desc_en: "",
                name_ru: "Франция",
                desc_ru: ""
```

**Comment by RobinHerbots** [comment]
@macfurin , 

Can you send a pull request with the correction.

Thx
Robin

**Comment by macfurin** [comment]
Hello @RobinHerbot, I send pull request #4

**Comment by Flo354** [comment]
Hi there,

Latest release doesn't contain the fix. Could you release a version with the fix please?

Thanks,

**Comment by RobinHerbots** [comment]
@Flo354 , 

Done
